services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: green502 # root 비밀번호 설정
      MYSQL_DATABASE: youp-db # 기본 생성할 데이터베이스
      MYSQL_USER: youp_user # 사용자 생성
      MYSQL_PASSWORD: green502 # 사용자 비밀번호 설정
    ports:
      - "3306:3306" # 호스트의 포트와 컨테이너의 포트 매핑
    volumes:
      - db_data:/var/lib/mysql # 데이터베이스 데이터가 저장될 경로
    networks:
      - my_network

volumes:
  db_data:


networks:
  my_network: